# Generated by Django 3.0.8 on 2020-08-02 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllCoupons',
            new_name='AllCoupon',
        ),
    ]
