# Generated by Django 3.0.8 on 2020-08-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20200803_0345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllCoupon',
        ),
    ]
