# Generated by Django 3.0.8 on 2020-08-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon', '0003_delete_allcoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_Number', models.PositiveIntegerField()),
                ('card_valid', models.DateField()),
                ('card_user_id', models.PositiveIntegerField()),
                ('card_user_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
