# Generated by Django 3.0.8 on 2020-08-03 10:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon', '0004_allcoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, max_length=30)),
                ('scannedAt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.AllCoupon')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
