# Generated by Django 3.0.8 on 2020-08-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_couponhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponhistory',
            name='card_number',
            field=models.PositiveIntegerField(),
        ),
    ]
