# Generated by Django 3.0.8 on 2020-10-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_auto_20200804_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponhistory',
            options={'verbose_name': 'Scanned History', 'verbose_name_plural': 'Scanned History'},
        ),
    ]
