# Generated by Django 3.0.8 on 2020-07-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNo',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
