# Generated by Django 3.0.8 on 2020-07-20 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProfile', '0006_auto_20200715_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Bussiness_Type',
            field=models.CharField(choices=[(1, 'test1'), (2, 'test2'), (3, 'test3'), (4, 'test4')], default='test1', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
