# Generated by Django 3.0.8 on 2020-07-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0011_auto_20200724_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discount_provided',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
