# Generated by Django 3.0.8 on 2020-10-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0012_auto_20200725_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Partner Profile', 'verbose_name_plural': 'Partner Profile'},
        ),
    ]
